version: "2.1"

volumes:
  videos:
  x11:

services:
  potal-receiver:
    image: portal
    restart: always
    build: ./portal
    privileged: true # run in privileged mode for easy access to soundcards and cameras
    volumes:
      - videos:/videos/
      - x11:/tmp/.X11-unix
    devices:
      - /dev/dri
    group_add:
      - video
    environment:
      - SENDER_OR_RECEIVER=receiver

  potal-sender:
    restart: always
    build: ./portal
    privileged: true # run in privileged mode for easy access to soundcards and cameras
    volumes:
      - videos:/videos/
      - x11:/tmp/.X11-unix
    ports:
      - "8888:8888/udp"
      - "8888:8888/tcp"
    devices:
      - /dev/dri
    group_add:
      - video
    environment:
      - SENDER_OR_RECEIVER=sender

  xserver:
    image: balenablocks/xserver
    restart: always
    privileged: true
    volumes:
      - "x11:/tmp/.X11-unix"
    environment:
      - CURSOR=false
