version: "2.1"

volumes:
  x11:
  netdatacache:
  netdatalib:

services:
  potal-receiver:
    image: portal
    build: ./portal
    restart: always
    privileged: true # run in privileged mode for easy access to soundcards and cameras
    depends_on:
      - xserver
    volumes:
      - x11:/tmp/.X11-unix
    devices:
      - /dev/dri
    group_add:
      - video
    environment:
      - SENDER_OR_RECEIVER=receiver

  potal-sender:
    build: ./portal
    restart: always
    privileged: true # run in privileged mode for easy access to soundcards and cameras
    volumes:
      - x11:/tmp/.X11-unix
    ports:
      - "8888:8888/udp"
      - "8888:8888/tcp"
    devices:
      - /dev/dri
    group_add:
      - video
    environment:
      - SENDER_OR_RECEIVER = sender

  xserver:
    image: balenablocks/xserver
    restart: always
    privileged: true
    volumes:
      - "x11:/tmp/.X11-unix"
    environment:
      - CURSOR=false

  netdata:
    #image: bh.cr/gh_odyslam/netdatablock
    build: ./NetdataBlock/netdata
    privileged: true
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.sysfs: 1
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata

  mdns-advertise:
    #image: bh.cr/gh_nucleardreamer/mdns-advertise
    build: ./mdns-advertise
    restart: "always"
    privileged: true
    network_mode: host
    labels:
      io.balena.features.dbus: "1"
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
